In [1]:
%matplotlib inline


=========================================================
Principal components analysis (PCA)
=========================================================

These figures aid in illustrating how a point cloud
can be very flat in one direction--which is where PCA
comes in to choose a direction that is not flat.




In [2]:
print(__doc__)
from sklearn.decomposition import PCA

from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

Automatically created module for IPython interactive environment


In [4]:
import os
os.getcwd()

'/Users/xling/Dropbox/MORB K-Rich/PCA/2017 AGU/PCA/examples'

In [5]:
# Import data
dataset = pd.read_csv('/Users/xling/Dropbox/MORB K-Rich/PCA/2017 AGU/PCA/marStandardized.csv')
isotopes = dataset.iloc[:,4:9].values
isotopes

array([[-0.43246313, -1.38360334, -0.75967948,  1.25879593,  0.73632812],
       [-0.3046918 , -1.08875849, -0.55623528,  1.40720613,  0.77195873],
       [-0.50816891, -1.58076556, -0.89015017,  1.52980586,  0.95605023],
       ..., 
       [ 0.32886857,  1.17161092,  0.34115834, -0.42533717,  0.40377574],
       [ 0.26856287,  1.4014659 ,  0.68442127, -0.62536831, -0.22569842],
       [ 0.26857371,  1.40208713,  0.6844726 , -0.62536831, -0.22569842]])

In [13]:
# PCA
pca = PCA ()
pca.fit(isotopes)
# by default: PCA(copy=True, iterated_power="auto", n_components = all, random_state = None, svd_colver="auto", tol=0.0, whiten=False)
print ("The explained_variance_ratio are:", pca.explained_variance_ratio_)
# get_precision(): compute data precision matrix with the generative model
pca.get_precision()
print ("the", pca.get_precision())

The explained_variance_ratio are: [ 0.63238983  0.30424696  0.03551706  0.02395309  0.00389306]
the [[ 15.6219256    3.92936988 -19.84803805   1.38911673  -7.92102326]
 [  3.92936988   6.56283026  -8.88403066   2.92209047  -2.46823768]
 [-19.84803805  -8.88403066  29.24919267  -3.84372997  11.27664208]
 [  1.38911673   2.92209047  -3.84372997   5.69892259  -4.90969671]
 [ -7.92102326  -2.46823768  11.27664208  -4.90969671   8.97391026]]


In [14]:
score = pca.score_samples(isotopes)
score

array([ -3.12511545,  -3.20735609,  -3.63451126,  -3.52768644,
        -4.19405184,  -3.60639801,  -4.62695434,  -4.04893638,
        -4.6792331 ,  -6.53500692,  -3.64037397,  -5.01859843,
        -4.46588196,  -3.74916725,  -5.2169964 ,  -4.70578604,
        -4.7115938 ,  -4.77150315,  -4.18532288,  -3.89146417,
        -6.00190223,  -3.51025981,  -4.79330033,  -5.88514056,
        -5.88039851,  -4.1539008 ,  -3.65772871,  -4.98317636,
        -3.87635768,  -5.01527901,  -2.81367735,  -2.84573374,
        -2.62582896,  -3.26286013,  -3.39453399,  -2.86677335,
        -3.27546912,  -2.69741534,  -3.01664138,  -3.25877329,
        -3.09160905,  -2.73226388,  -2.74331601,  -2.524114  ,
        -2.8326203 ,  -2.71286951,  -2.80013553,  -2.58821278,
        -2.79655065,  -3.37418152,  -3.2027094 ,  -2.70287055,
        -2.65069294,  -2.5752188 ,  -2.28951822,  -2.28049223,
        -2.10369603,  -2.09299629,  -2.36067662,  -2.45353072,
        -1.92646317,  -1.90718344,  -1.96067166,  -1.88